name: Sync Calendar

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Set up service account credentials
        run: |
          echo '${{secrets.GCP_SERVICE_ACCOUNT_KEY}}' > /tmp/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV
        
      - name: Run sync
        env:
          NOTION_API_TOKEN: ${{secrets.NOTION_API_TOKEN}}
          NOTION_EVENTS_DATABASE_ID: ${{secrets.NOTION_EVENTS_DATABASE_ID}}
        run: npm run sync
